version: '3.1'

services:
  pneuma-mysql:
    image: mysql:8.0
    restart: always
    network_mode: bridge
    command: --default-authentication-plugin=mysql_native_password
    container_name: pneuma-mysql
    volumes:
      - pneuma-mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${PNEUMA_WT_MYSQL_PASSWORD}
  
  adminer:
    image: adminer
    restart: always
    network_mode: bridge
    links:
      - 'pneuma-mysql:db'
    ports:
      - 8180:8080

volumes:
  pneuma-mysql: